In [6]:
import pandas as pd

# Read CSV from folder

In [8]:
df = pd.read_csv("Data/house_price_20_rows.csv")
df

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
0,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
2,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
4,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby
5,6,600,1,Ghaziabad,No,35.0,2026-02-18,Budget home
6,7,900,2,Noida,Yes,45.0,2026-02-25,Near market
7,8,1100,3,Delhi,Yes,65.0,2026-03-04,Near metro
8,9,1400,3,Gurgaon,No,90.0,2026-03-15,IT hub area
9,10,1800,4,Delhi,Yes,120.0,2026-03-22,Large house
10,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
11,12,950,2,Jaipur,No,42.0,2026-04-10,Good connectivity
12,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area
13,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
14,15,850,2,Ghaziabad,Yes,38.0,2026-05-09,Near school
15,16,1050,2,Delhi,No,58.0,2026-05-17,NaN
16,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing
17,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
18,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property
19,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available

# Read CSV data with Separator \t , " ; | ==> using sep = "" parameter

In [9]:
df = pd.read_csv("Data/house_price_20_rows_colon_separated.csv", sep = ":")
df

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
0,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
2,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
4,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby
5,6,600,1,Ghaziabad,No,35.0,2026-02-18,Budget home
6,7,900,2,Noida,Yes,45.0,2026-02-25,Near market
7,8,1100,3,Delhi,Yes,65.0,2026-03-04,Near metro
8,9,1400,3,Gurgaon,No,90.0,2026-03-15,IT hub area
9,10,1800,4,Delhi,Yes,120.0,2026-03-22,Large house
10,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
11,12,950,2,Jaipur,No,42.0,2026-04-10,Good connectivity
12,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area
13,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
14,15,850,2,Ghaziabad,Yes,38.0,2026-05-09,Near school
15,16,1050,2,Delhi,No,58.0,2026-05-17,NaN
16,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing
17,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
18,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property
19,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available

# show 5 row from top using head()

In [10]:
df.head()

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
0,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
2,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
4,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby

# show 5 row from tail()

In [11]:
df.tail()

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
15,16,1050,2,Delhi,No,58.0,2026-05-17,NaN
16,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing
17,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
18,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property
19,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available

# Show Random data using sample()

In [12]:
df.sample(5)

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
13,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
10,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
12,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area

# Information of your data using info()

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   House_ID         20 non-null     int64
 1   House_Area_sqft  20 non-null     int64
 2   Bedrooms         20 non-null     int64
 3   Location         20 non-null     object
 4   Parking          20 non-null     object
 5   Price_Lakhs      19 non-null     float64
 6   Sale_Date        20 non-null     object
 7   Owner_Note       19 non-null     object
dtypes: float64(1), int64(3), object(4)
memory usage: 1.4+ KB

# See Row & columns number using shape

In [15]:
df.shape

(20, 8)

# See Columns name using columns

In [17]:
df.columns

Index(['House_ID', 'House_Area_sqft', 'Bedrooms', 'Location', 'Parking',
       'Price_Lakhs', 'Sale_Date', 'Owner_Note'],
      dtype='object')

# get unique values of a single column using unique()

In [19]:
df["Location"].unique()

array(['Delhi', 'Noida', 'Gurgaon', 'Ghaziabad', 'Lucknow', 'Jaipur',
       'Pune', 'Mumbai'], dtype=object)

# value counts() ==> How many times same values occur in a single column

In [21]:
df["Parking"].value_counts()

Parking
Yes    14
No      6
Name: count, dtype: int64

# Mathematical formula on your dataset mean , std, max , min, .., etc using ==> describe()

In [25]:

df.describe()

       House_ID  House_Area_sqft  Bedrooms  Price_Lakhs
count  20.00000        20.000000  20.00000    19.000000
mean   10.50000      1155.000000   2.60000    72.368421
std     5.91608       392.997924   0.88258    42.388692
min     1.00000       500.000000   1.00000    25.000000
25%     5.75000       887.500000   2.00000    41.000000
50%    10.50000      1125.000000   3.00000    65.000000
75%    15.25000      1412.500000   3.00000    84.000000
max    20.00000      2000.000000   4.00000   190.000000

# Find Single column mean using mean()

In [26]:
df["House_ID"].mean()

np.float64(10.5)

# Show Every NaN row using axis = 1

In [27]:
df[df.isnull().any(axis = 1)]

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
15,16,1050,2,Delhi,No,58.0,2026-05-17,NaN
19,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available

# fill NaN valus using fillna()

In [29]:
df["Owner_Note"] = df["Owner_Note"].fillna(0)
df

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
0,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
2,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
4,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby
5,6,600,1,Ghaziabad,No,35.0,2026-02-18,Budget home
6,7,900,2,Noida,Yes,45.0,2026-02-25,Near market
7,8,1100,3,Delhi,Yes,65.0,2026-03-04,Near metro
8,9,1400,3,Gurgaon,No,90.0,2026-03-15,IT hub area
9,10,1800,4,Delhi,Yes,120.0,2026-03-22,Large house
10,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
11,12,950,2,Jaipur,No,42.0,2026-04-10,Good connectivity
12,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area
13,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
14,15,850,2,Ghaziabad,Yes,38.0,2026-05-09,Near school
15,16,1050,2,Delhi,No,58.0,2026-05-17,0
16,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing
17,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
18,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property
19,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available

# Drop row where you get NaN ==> using dropna()

In [30]:
df = df.dropna()
df

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
0,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
2,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
4,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby
5,6,600,1,Ghaziabad,No,35.0,2026-02-18,Budget home
6,7,900,2,Noida,Yes,45.0,2026-02-25,Near market
7,8,1100,3,Delhi,Yes,65.0,2026-03-04,Near metro
8,9,1400,3,Gurgaon,No,90.0,2026-03-15,IT hub area
9,10,1800,4,Delhi,Yes,120.0,2026-03-22,Large house
10,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
11,12,950,2,Jaipur,No,42.0,2026-04-10,Good connectivity
12,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area
13,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
14,15,850,2,Ghaziabad,Yes,38.0,2026-05-09,Near school
15,16,1050,2,Delhi,No,58.0,2026-05-17,0
16,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing
17,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
18,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property

# Remove pandas Default index and use your own from datase using index_col

In [32]:
df = pd.read_csv("Data/house_price_20_rows.csv", index_col = "House_Area_sqft")
df

,House_ID,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
House_Area_sqft,,,,,,,
500,1,1,Delhi,Yes,25.0,2026-01-05,Café nearby
800,2,2,Noida,Yes,40.0,2026-01-12,Good location
1000,3,2,Delhi,No,60.0,2026-01-20,Near metro
1200,4,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
1500,5,3,Noida,Yes,80.0,2026-02-10,Park nearby
600,6,1,Ghaziabad,No,35.0,2026-02-18,Budget home
900,7,2,Noida,Yes,45.0,2026-02-25,Near market
1100,8,3,Delhi,Yes,65.0,2026-03-04,Near metro
1400,9,3,Gurgaon,No,90.0,2026-03-15,IT hub area
1800,10,4,Delhi,Yes,120.0,2026-03-22,Large house
700,11,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
950,12,2,Jaipur,No,42.0,2026-04-10,Good connectivity
1250,13,3,Pune,Yes,70.0,2026-04-18,Near office area
1600,14,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
850,15,2,Ghaziabad,Yes,38.0,2026-05-09,Near school
1050,16,2,Delhi,No,58.0,2026-05-17,NaN
1300,17,3,Noida,Yes,72.0,2026-06-03,Owner note missing
1450,18,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
2000,19,4,Mumbai,No,190.0,2026-06-20,Premium property
1150,20,3,Pune,Yes,NaN,2026-06-28,Price not available

# Remove Duplicate Value

In [34]:
df.duplicated().sum()

np.int64(0)

# usecols

In [40]:
df = pd.read_csv("Data/house_price_20_rows.csv", usecols = ["House_ID", "Bedrooms","House_Area_sqft", "Price_Lakhs"])
df.corr()

                 House_ID  House_Area_sqft  Bedrooms  Price_Lakhs
House_ID         1.000000         0.467458  0.473758     0.482576
House_Area_sqft  0.467458         1.000000  0.939275     0.925802
Bedrooms         0.473758         0.939275  1.000000     0.877945
Price_Lakhs      0.482576         0.925802  0.877945     1.000000

# Correlation b/w the columns it's working on only numbers data

In [38]:
df = pd.read_csv("Data/house_price_20_rows.csv", usecols = ["House_ID", "Bedrooms","House_Area_sqft", "Price_Lakhs"])
df.corr()

                 House_ID  House_Area_sqft  Bedrooms  Price_Lakhs
House_ID         1.000000         0.467458  0.473758     0.482576
House_Area_sqft  0.467458         1.000000  0.939275     0.925802
Bedrooms         0.473758         0.939275  1.000000     0.877945
Price_Lakhs      0.482576         0.925802  0.877945     1.000000

# Modify the date data into dateformat using parse_dates parameter in read_csv()

In [48]:
df = pd.read_csv("Data/house_price_20_rows.csv", parse_dates= ["Sale_Date"])
df

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
0,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
2,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
4,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby
5,6,600,1,Ghaziabad,No,35.0,2026-02-18,Budget home
6,7,900,2,Noida,Yes,45.0,2026-02-25,Near market
7,8,1100,3,Delhi,Yes,65.0,2026-03-04,Near metro
8,9,1400,3,Gurgaon,No,90.0,2026-03-15,IT hub area
9,10,1800,4,Delhi,Yes,120.0,2026-03-22,Large house
10,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
11,12,950,2,Jaipur,No,42.0,2026-04-10,Good connectivity
12,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area
13,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
14,15,850,2,Ghaziabad,Yes,38.0,2026-05-09,Near school
15,16,1050,2,Delhi,No,58.0,2026-05-17,NaN
16,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing
17,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
18,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property
19,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available

# get the year, month, day from the date column

In [50]:
df["Year"] = df["Sale_Date"].dt.year
df["Month"] = df["Sale_Date"].dt.month
df["Day"] = df["Sale_Date"].dt.day
df

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note,Year,Month,Day
0,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby,2026,1,5
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location,2026,1,12
2,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro,2026,1,20
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area,2026,2,3
4,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby,2026,2,10
5,6,600,1,Ghaziabad,No,35.0,2026-02-18,Budget home,2026,2,18
6,7,900,2,Noida,Yes,45.0,2026-02-25,Near market,2026,2,25
7,8,1100,3,Delhi,Yes,65.0,2026-03-04,Near metro,2026,3,4
8,9,1400,3,Gurgaon,No,90.0,2026-03-15,IT hub area,2026,3,15
9,10,1800,4,Delhi,Yes,120.0,2026-03-22,Large house,2026,3,22
10,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area,2026,4,2
11,12,950,2,Jaipur,No,42.0,2026-04-10,Good connectivity,2026,4,10
12,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area,2026,4,18
13,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area,2026,5,1
14,15,850,2,Ghaziabad,Yes,38.0,2026-05-09,Near school,2026,5,9
15,16,1050,2,Delhi,No,58.0,2026-05-17,NaN,2026,5,17
16,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing,2026,6,3
17,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment,2026,6,12
18,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property,2026,6,20
19,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available,2026,6,28

# Save the csv using to_csv()

In [51]:
df.to_csv("My_own_clean_data.csv")

# names parameter --> When you want provide column names manually.

In [53]:
df = pd.read_csv("Data/house_price_20_rows.csv", names = ["ID","Area", "rooms"	,"city","Parking","Price","Date_s","Note"])
df

,ID,Area,rooms,city,Parking,Price,Date_s,Note
0,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
1,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby
2,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
3,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro
4,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
5,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby
6,6,600,1,Ghaziabad,No,35.0,2026-02-18,Budget home
7,7,900,2,Noida,Yes,45.0,2026-02-25,Near market
8,8,1100,3,Delhi,Yes,65.0,2026-03-04,Near metro
9,9,1400,3,Gurgaon,No,90.0,2026-03-15,IT hub area
10,10,1800,4,Delhi,Yes,120.0,2026-03-22,Large house
11,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
12,12,950,2,Jaipur,No,42.0,2026-04-10,Good connectivity
13,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area
14,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
15,15,850,2,Ghaziabad,Yes,38.0,2026-05-09,Near school
16,16,1050,2,Delhi,No,58.0,2026-05-17,NaN
17,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing
18,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
19,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property
20,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available

# remove bad lines using --> on_bad_lines= "skip""

In [54]:
df = pd.read_csv("Data/information_with_bad_data.csv", on_bad_lines= "skip" )
df

    ID    Name  Age     City  Marks
0    1   Rahul   20    Delhi     85
1    2   Priya   21   Mumbai     90
2    3    Amit   19  Lucknow     78
3    4    Neha   22   Kanpur     88
4    5   Rohit   20     Agra     76
5    6  Anjali   21   Jaipur     92
6    7   Vikas   23    Delhi     81
7    8   Sneha   20    Noida     89
8    9   Arjun   22   Meerut     74
9   10   Pooja   21     Agra     95
10  12  Kavita   22    Delhi     87
11  13  Suresh   24   Kanpur     72
12  15  Deepak   23     Agra     69
13  16  Simran   21   Jaipur     94
14  17   Karan   20    Delhi     83
15  19   Varun   19   Kanpur     77
16  20   Nisha   21   Mumbai     93

# Get CSV data from URL

In [57]:
url  = "https://raw.githubusercontent.com/pcsanwald/kaggle-titanic/master/train.csv"
url_df = pd.read_csv(url)
url_df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# read_excel()

In [ ]:
# name, index_col, header, usecols, skiprows, dtype, parse_date

In [2]:
import pandas as pd
df_excel = pd.read_excel("Data/house_price_20_rows.xlsx")
df_excel

,House_ID,House_Area_sqft,Bedrooms,Location,Parking,Price_Lakhs,Sale_Date,Owner_Note
0,1,500,1,Delhi,Yes,25.0,2026-01-05,Café nearby
1,2,800,2,Noida,Yes,40.0,2026-01-12,Good location
2,3,1000,2,Delhi,No,60.0,2026-01-20,Near metro
3,4,1200,3,Gurgaon,Yes,75.0,2026-02-03,Premium area
4,5,1500,3,Noida,Yes,80.0,2026-02-10,Park nearby
5,6,600,1,Ghaziabad,No,35.0,2026-02-18,Budget home
6,7,900,2,Noida,Yes,45.0,2026-02-25,Near market
7,8,1100,3,Delhi,Yes,65.0,2026-03-04,Near metro
8,9,1400,3,Gurgaon,No,90.0,2026-03-15,IT hub area
9,10,1800,4,Delhi,Yes,120.0,2026-03-22,Large house
10,11,700,2,Lucknow,Yes,32.0,2026-04-02,Quiet area
11,12,950,2,Jaipur,No,42.0,2026-04-10,Good connectivity
12,13,1250,3,Pune,Yes,70.0,2026-04-18,Near office area
13,14,1600,4,Mumbai,Yes,150.0,2026-05-01,Sea-facing area
14,15,850,2,Ghaziabad,Yes,38.0,2026-05-09,Near school
15,16,1050,2,Delhi,No,58.0,2026-05-17,NaN
16,17,1300,3,Noida,Yes,72.0,2026-06-03,Owner note missing
17,18,1450,3,Gurgaon,Yes,88.0,2026-06-12,Modern apartment
18,19,2000,4,Mumbai,No,190.0,2026-06-20,Premium property
19,20,1150,3,Pune,Yes,NaN,2026-06-28,Price not available